# Generated by Django 3.2 on 2023-12-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='mesa',
            table='Mesa',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='Reserva',
        ),
    ]
